version: "3"

volumes:
  swallowtail_zookeeper_data: {}
  swallowtail_zookeeper_datalog: {}
  swallowtail_kafka_data: {}

services:
  ### --- Infrastructure --- ###

  ## -- postgres -- ##
  postgres:
    build:
      context: .
      dockerfile: ./infrastructure/postgres/Dockerfile
    image: i.swallowtail.postgres 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=swallowtail
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  postgres_test:
    build:
      context: .
      dockerfile: ./infrastructure/postgres/Dockerfile
    image: test.swallowtail.i.postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=swallowtail_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ### --- RPC Layer --- ###

  ### --- APIs --- ###

  ### --- Backend --- ###
  swallowtail.s.account:
    hostname: swallowtail-s-account
    image: swallowtail.s.account
    ports:
      - "8001:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres

  swallowtail.s.discord:
    hostname: swallowtail-s-discord
    image: swallowtail.s.discord
    ports:
      - "8002:8000"
    env_file:
      - .envs/postgres.env
      - .envs/discord.env
    depends_on:
      - postgres

  swallowtail.s.satoshi:
    hostname: swallowtail-s-satoshi
    image: swallowtail.s.satoshi
    ports:
      - "8003:8000"
    env_file:
      - .envs/postgres.env
      - .envs/discord.env
      - .envs/binance.env
      - .envs/twitter.env

  swallowtail.s.googlesheets:
    hostname: swallowtail-s-googlesheets
    image: swallowtail.s.googlesheets
    ports:
      - "8004:8000"

  swallowtail.s.binance:
    hostname: swallowtail-s-binance
    image: swallowtail.s.binance
    ports:
      - "8005:8000"
    env_file:
      - .envs/postgres.env
    depends_on:
      - postgres

  swallowtail.coingecko:
    hostname: swallowtail-s-coingecko
    image: swallowtail.s.coingecko
    ports:
      - "8006:8006"
    depends_on:
      - postgres
