version: "3"

networks:
  envoymesh: {}

volumes:
  swallowtail_postgres_data: {}
  swallowtail_postgres_data_backup: {}
  swallowtail_zookeeper_data: {}
  swallowtail_zookeeper_datalog: {}
  swallowtail_kafka_data: {}

services:
  ### --- Infrastructure --- ###
  postgres:
    build:
      context: .
      dockerfile: ./infrastructure/postgres/Dockerfile
    image: i.postgres 
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=swallowtail
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - swallowtail_postgres_data:/var/lib/postgresql/data
      - swallowtail_postgres_data_backup:/backups
    env_file:
      ./.envs/.local/.postgres

  ### --- RPC Layer --- ###

  ### --- APIs --- ###

  ### --- Backend --- ###
  s.twitter:
    build:
      context: .
      dockerfile: ./s.twitter/Dockerfile
    environment:
      - TWITTER_API_KEY=O6Jj1DEFAF6izebAGiYr8vob1
      - TWITTER_ACCESS_TOKEN=1367536652571332613-CtFx2BKIQmB3Ixcs2XOUhweufwGpef
      - TWITTER_ACCESS_TOKEN_SECRET=36JtEnFiETCwLdkTgAgWSegmhuBfheKDdozfYAZ5VMcb5
      - TWITTER_API_SECRET=fE3J2HmVnlrl39yYpyTvvjaCItRZH3acNctHc0zvhYHKAv9CAG
      - TWITTER_BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAONkNQEAAAAARKMBqXDmZUn6Pb6q9E6j8586Mx8%3DWABey7n5XQoTQKxT10oWdhFGx22YJbcbDQEE1hVmTNjrblL55K
      - DISCORD_API_TOKEN=ODE2ODAzMTYyOTg3ODIzMTMx.YEAROQ.3-rwSXyzIYK7zcfRyYdHpornqcM
    image: s.twitter
